name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest #VM that GH actions will run on
    steps:
      - uses: actions/checkout@v3
      - name: install packages
        run: make python_install
      - name: format
        run: make python_format
      - name: lint
        run: make python_lint
      - name: test
        run: make python_test